export const gizzaBackEndAPIConfig = {
  searchAllCategoriesUrl: '/gizza/api/categorie/get/all',
  searchAllPizzasUrl: '/gizza/api/pizza/get/all',
  searchAllDrinksUrl: '/gizza/api/boisson/get/all',
  searchAllDessertsUrl: '/gizza/api/dessert/get/all',
  searchItemsByCategoryUrl: '/gizza/api/categorie/get/by/id/',
  searchTestUrl: 'https://geo.api.gouv.fr/departements',
  searchAllCategoriesByTypeUrl:'/gizza/api/categorie/get/by/type/',
  addCategoryUrl:'/gizza/api/categorie/add',
  updateCategoryUrl:'/gizza/api/categorie/update',
  deleteCategoryUrl:'/gizza/api/categorie/delete/',
  addPizzaUrl:'/gizza/api/pizza/add',
  updatePizzaUrl:'/gizza/api/pizza/update/',
  deletePizzaUrl:'/gizza/api/delete/',
  addBoissonUrl:'/gizza/api/boisson/add',
  updateBoissonUrl:'/gizza/api/boisson/update',
  deleteBoissonUrl:'/gizza/api/boisson/delete/',
  addDessertUrl:'/gizza/api/dessert/add',
  updateDessertUrl:'/gizza/api/dessert/update',
  deleteDessertUrl:'/gizza/api/dessert/delete/',
};
